version: "3.7"

##############
#
# subir primeiro na versao v3.3.1 e depois na  latest
# Execute o mando para migrar o banco:
#
# bundle exec rails db:chatwoot_prepare
#
#############

services:
  chatwoot_app:
    image: chatwoot/chatwoot:latest
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    entrypoint: docker/entrypoints/rails.sh
    restart: unless-stopped
    volumes:
      - chatwoot_data:/app/storage 
    networks:
      - minha_rede
    environment:
      - INSTALLATION_NAME=chatwoot
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - SECRET_KEY_BASE=123458bb7ef6402f6a8bcf5d3be54321
      - FRONTEND_URL=https://seu dominio aqui  #coloque seu dominio aqui 
      - DEFAULT_LOCALE=pt_BR
      - FORCE_SSL=true
      - ENABLE_ACCOUNT_SIGNUP=false
      - REDIS_URL=redis://redis:6379
      - POSTGRES_HOST=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=senha do postegres aqui # coloque a senha do seu postegre aqui 
      - POSTGRES_DATABASE=chatwoot
      - ACTIVE_STORAGE_SERVICE=local
      - RAILS_LOG_TO_STDOUT=true
      - USE_INBOX_AVATAR_FOR_BOT=true
      # Servidor de Email Gmail cloque so se quizer obs nao é obrigartorio 
      - MAILER_SENDER_EMAIL=Chatwoot <seuemail@gmail.com>  # sntro da barras coloque seu email se quizer 
      - SMTP_DOMAIN=gmail.com # seu dominio de smtp
      - SMTP_ADDRESS=smtp.gmail.com # aqui esta usando o do google pode usar qualquer um que quizer 
      - SMTP_PORT=587 # porta smtp
      - SMTP_USERNAME=seuemail@gmail.com # seu email do smtp 
      - SMTP_PASSWORD=suasenhadeapp # senha do smtp ou do app do google 
      - SMTP_AUTHENTICATION=login 
      - SMTP_ENABLE_STARTTLS_AUTO=true
      - SMTP_OPENSSL_VERIFY_MODE=peer
      - MAILER_INBOUND_EMAIL_DOMAIN=seuemail@gmail.com # mesmo email do smtp 
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M


  chatwoot_sidekiq:
    image: chatwoot/chatwoot:latest
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - chatwoot_data:/app/storage
    networks:
      - minha_rede
    environment:
      - INSTALLATION_NAME=chatwoot
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - SECRET_KEY_BASE=123458bb7ef6402f6a8bcf5d3be54321
      - FRONTEND_URL=https://seu dominio aqui  #coloque seu dominio aqui 
      - DEFAULT_LOCALE=pt_BR
      - FORCE_SSL=true
      - ENABLE_ACCOUNT_SIGNUP=false
      - REDIS_URL=redis://redis:6379
      - POSTGRES_HOST=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=senha do postegres aqui # coloque a senha do seu postegre aqui 
      - POSTGRES_DATABASE=chatwoot
      - ACTIVE_STORAGE_SERVICE=local
      - RAILS_LOG_TO_STDOUT=true
      - USE_INBOX_AVATAR_FOR_BOT=true
      # Servidor de Email Gmail cloque so se quizer obs nao é obrigartorio 
      - MAILER_SENDER_EMAIL=Chatwoot <seuemail@gmail.com>  # sntro da barras coloque seu email se quizer 
      - SMTP_DOMAIN=gmail.com # seu dominio de smtp
      - SMTP_ADDRESS=smtp.gmail.com # aqui esta usando o do google pode usar qualquer um que quizer 
      - SMTP_PORT=587 # porta smtp
      - SMTP_USERNAME=seuemail@gmail.com # seu email do smtp 
      - SMTP_PASSWORD=suasenhadeapp # senha do smtp ou do app do google 
      - SMTP_AUTHENTICATION=login 
      - SMTP_ENABLE_STARTTLS_AUTO=true
      - SMTP_OPENSSL_VERIFY_MODE=peer
      - MAILER_INBOUND_EMAIL_DOMAIN=seuemail@gmail.com # mesmo email do smtp 
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

volumes:
  chatwoot_data:
    external: true
    name: chatwoot_data

networks:
  minha_rede:
    external: true
    name: minha_rede
    
#configurado para usar com 1panel  video aula no canal do youtube @SYSTEMHELP link https://www.youtube.com/@SYSTEMHELP
## GOSTOU QUE TAL ME DAR UM CAFE  AQUI ESTA MEU PIX : CNPJ :  48.590.314/0001-18 
##  OBRIGADO 
