version: "3.7"

services:
  mongodb:
    image: mongo:7
    command: mongod --port 27017
    restart: unless-stopped
    networks:
      - minha_rede
    volumes:
      - mongodb_data:/data/db
      - mongodb_configdb_data:/data/configdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user para seu mongo  #coloque aqui o user para seu mongo 
      - MONGO_INITDB_ROOT_PASSWORD=senha para seu mongo # colque aqui uma senha para seu mongo 
      - PUID=1000
      - PGID=1000
    ports:
      - 27017:27017
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

volumes:
  mongodb_data:
    external: true
    name: mongodb_data
  mongodb_configdb_data:
    external: true
    name: mongodb_configdb_data

networks:
  minha_rede:
    external: true
    name: minha_rede

#configurado para usar com 1panel  video aula no canal do youtube @SYSTEMHELP link https://www.youtube.com/@SYSTEMHELP
## GOSTOU QUE TAL ME DAR UM CAFE  AQUI ESTA MEU PIX : CNPJ :  48.590.314/0001-18 
##  OBRIGADO 
